# -*- coding: utf-8 -*-
PLUGINS_DB = [
    # ==================== FAZA 1 - System ====================
    {"phase": 1, "name": "update", "command": "opkg update", "type": "system", "desc": "Osvežavanje feed-ova"},
    {"phase": 1, "name": "secret-feed", "command": "wget -O - -q http://updates.mynonpublic.com/oea/feed | bash", "type": "system", "desc": "Softcam feed"},
    {"phase": 1, "name": "astra-sm", "command": "opkg install astra-sm", "type": "opkg", "desc": "Astra-sm"},
    {"phase": 1, "name": "wget", "command": "opkg install wget", "type": "opkg", "desc": "Wget"},
    {"phase": 1, "name": "curl", "command": "opkg install curl", "type": "opkg", "desc": "Curl"},
    {"phase": 1, "name": "python3-lxml", "command": "opkg install python3-lxml", "type": "opkg", "desc": "python3-lxml"},
    {"phase": 1, "name": "gstplayer", "command": "opkg install gstplayer", "type": "opkg", "desc": "GstPlayer"},
    {"phase": 1, "name": "streamlinksrv", "command": "opkg install streamlinksrv", "type": "opkg", "desc": "Streamlink srv"},
    {"phase": 1, "name": "python3-requests", "command": "opkg install python3-requests", "type": "opkg", "desc": "python3-requests"},
    {"phase": 1, "name": "python3-beautifulsoup4", "command": "opkg install python3-beautifulsoup4", "type": "opkg", "desc": "python3-beautifulsoup4"},
    {"phase": 1, "name": "cifs-utils", "command": "opkg install cifs-utils", "type": "opkg", "desc": "cifs-utils"},
    {"phase": 1, "name": "oscam-emu", "command": "opkg install enigma2-plugin-softcams-oscam-emu", "type": "opkg", "desc": "OSCam EMU Softcam"},
    
    # ==================== FAZA 2 - CiefpSettings ====================
    {"phase": 2, "name": "CiefpPlugins", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpPlugins/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp glavni plugin"},
    {"phase": 2, "name": "CiefpsettingsPanel", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpsettingsPanel/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Settings Panel"},
    {"phase": 2, "name": "CiefpSettingsDownloader", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpSettingsDownloader/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Downloader"},
    {"phase": 2, "name": "CiefpsettingsMotor", "command": "wget https://raw.githubusercontent.com/ciefp/CiefpsettingsMotor/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Motor"},
    {"phase": 2, "name": "CiefpSelectSatellite", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpSelectSatellite/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Select Satellite"},
    {"phase": 2, "name": "CiefpBouquetUpdater", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpBouquetUpdater/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Bouquet Updater"},
    {"phase": 2, "name": "CiefpChannelManager", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpChannelManager/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Channel Manager"},
    {"phase": 2, "name": "CiefpE2Converter", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpE2Converter/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp E2 Converter"},
    {"phase": 2, "name": "CiefpSatelliteXmlEditor", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpSatelliteXmlEditor/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Satellites XML Editor"},
    {"phase": 2, "name": "CiefpIPTVBouquets", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpIPTVBouquets/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp IPTV Bouquets"},
    {"phase": 2, "name": "CiefpWhitelistStreamrelay", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpWhitelistStreamrelay/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Whitelist Streamrelay"},
    {"phase": 2, "name": "CiefpSettingsStreamrelay", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpSettingsStreamrelay/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Streamrelay PY3"},# Pronađi ovu liniju i zameni je:
    {"phase": 2, "name": "CiefpSettingsT2miAbertis", "command": "AUTO", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp T2MI Abertis"},
    {"phase": 2, "name": "CiefpScreenGrab", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpScreenGrab/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Screen Grab"},
    {"phase": 2, "name": "CiefpMojTvEPG", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpMojTvEPG/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Moj TV EPG"},
    {"phase": 2, "name": "CiefpTvProgram", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpTvProgram/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp TV Program"},
    {"phase": 2, "name": "CiefpTvProgramSK", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpTvProgramSK/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp TV Program SK"},
    {"phase": 2, "name": "CiefpTvProgramA1HR", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpTvProgramA1HR/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp TV Program A1 HR"},
    {"phase": 2, "name": "CiefpTvTodayDE", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpTvTodayDE/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp TV Today DE"},
    {"phase": 2, "name": "CiefpEPGshare ", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpEPGshare/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp EPGshare"},
    {"phase": 2, "name": "CiefpTvProgramSBB", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpTvProgramSBB/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp TV Program SBB"},
    {"phase": 2, "name": "CiefpOscamEditor", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpOscamEditor/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Oscam Editor"},
    {"phase": 2, "name": "CiefpSatelliteAnalyzer", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpSatelliteAnalyzer/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Satellite Analyzer"},
    {"phase": 2, "name": "CiefpOpenDirectories", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpOpenDirectories/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Open Directories"},
    {"phase": 2, "name": "CiefpTMDBSearch", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpTMDBSearch/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp TMDB Search"},
    {"phase": 2, "name": "CiefpVibes", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpVibes/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Vibes"},
    {"phase": 2, "name": "CiefpKingSat", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpKingSat/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp KingSat"},
    {"phase": 2, "name": "CiefpParabolaCZ", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpParabolaCZ/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Parabola CZ"},
    {"phase": 2, "name": "CiefpRottenTomatoes", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpRottenTomatoes/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp RottenTomatoes"},
    {"phase": 2, "name": "CiefpOpenSubtitles", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpOpenSubtitles/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp OpenSubtitles"},
    {"phase": 2, "name": "CiefpSRTplayer", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpSRTplayer/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp SRT Player"},
    {"phase": 2, "name": "CiefpPicturePlayer", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/CiefpPicturePlayer/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Ciefp Picture Player"},
    {"phase": 2, "name": "TitloviBrowser", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/TitloviBrowser/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "Titlovi Browser"},
    {"phase": 2, "name": "WebCamE2PrenjSF", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/ciefp/WebCamE2PrenjSF/main/installer.sh -O - | /bin/sh", "type": "ciefp", "skip_reboot": True, "desc": "WebCam E2 PrenjSF"},

    # ==================== FAZA 3 - Feed Plugins (Stabilno) ====================
    {"phase": 3, "name": "AJPan", "command": "opkg install enigma2-plugin-extensions-ajpanel", "type": "opkg", "desc": "AjPanel"},
    {"phase": 3, "name": "EPGImport", "command": "opkg install enigma2-plugin-extensions-epgimport", "type": "opkg", "desc": "EPG Import"},
    {"phase": 3, "name": "EStalker", "command": "opkg install enigma2-plugin-extensions-estalker", "type": "opkg", "desc": "Stalker portal"},
    {"phase": 3, "name": "HDFRadio", "command": "opkg install enigma2-plugin-extensions-hdfradio", "type": "opkg", "desc": "HDF Radio"},
    {"phase": 3, "name": "OAWeather", "command": "opkg install enigma2-plugin-extensions-oaweather", "type": "opkg", "desc": "Vremenska prognoza"},
    {"phase": 3, "name": "StreamlinkWrapper", "command": "opkg install enigma2-plugin-extensions-streamlinkwrapper", "type": "opkg", "desc": "Streamlink podrška"},
    {"phase": 3, "name": "vavoo", "command": "opkg install enigma2-plugin-extensions-vavoo", "type": "opkg", "desc": "Vavoo TV"},
    {"phase": 3, "name": "XStreamity", "command": "opkg install enigma2-plugin-extensions-xstreamity", "type": "opkg", "desc": "XStreamity IPTV"},
    {"phase": 3, "name": "YouTube", "command": "opkg install enigma2-plugin-extensions-youtube", "type": "opkg", "desc": "YouTube TV"},
    {"phase": 3, "name": "ytdlpwrapper", "command": "opkg install enigma2-plugin-extensions-ytdlpwrapper", "type": "opkg", "desc": "yt-dlp podrška"},
    {"phase": 3, "name": "DCWKeyAdd", "command": "opkg install enigma2-plugin-extensions-auto-dcw-key-add", "type": "opkg", "desc": "Auto DCW key add"},
    {"phase": 3, "name": "chromium", "command": "opkg install enigma2-plugin-extensions-chromium", "type": "opkg", "desc": "Pretraživač"},
    {"phase": 3, "name": "WebkitHbbTV", "command": "opkg install enigma2-plugin-extensions-webkithbbtv", "type": "opkg", "desc": "HbbTV podrška"},

    # ==================== RUČNA INSTALACIJA (Third Party Scripts) ====================
    {"phase": 99, "name": "Astronomy", "command": "wget https://raw.githubusercontent.com/emilnabil/download-plugins/refs/heads/main/astronomy/installer.sh -O - | /bin/sh", "type": "thirdparty", "desc": "Astronomy"},
    {"phase": 99, "name": "XStreamity", "command": "wget https://raw.githubusercontent.com/biko-73/xstreamity/main/installer.sh -qO - | /bin/sh", "type": "thirdparty", "desc": "X-Streamity"},
    {"phase": 99, "name": "XKlass", "command": "wget https://dreambox4u.com/emilnabil237/plugins/xklass/installer.sh -O - | /bin/sh", "type": "thirdparty", "desc": "XKlass"},
    {"phase": 99, "name": "Estalker", "command": "wget https://github.com/emilnabil/download-plugins/raw/refs/heads/main/EStalker/EStalker.sh -O - | /bin/sh", "type": "thirdparty", "desc": "EStalker"},
    {"phase": 99, "name": "RaedQuickSignal", "command": "wget https://raw.githubusercontent.com/fairbird/RaedQuickSignal/main/installer.sh -O - | /bin/sh", "type": "thirdparty", "desc": "Raed Quick Signal"},
    {"phase": 99, "name": "AjPanel", "command": "wget https://raw.githubusercontent.com/biko-73/AjPanel/main/installer.sh -O - | /bin/sh", "type": "thirdparty", "desc": "AjPanel"},
    {"phase": 99, "name": "KeyAdder", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/fairbird/KeyAdder/main/installer.sh -O - |/bin/sh", "type": "thirdparty", "desc": "Key Adder"},
    {"phase": 99, "name": "DCWKeyAdd", "command": "wget https://raw.githubusercontent.com/Ham-ahmed/294/refs/heads/main/auto-dcw-key-add_v1.0.5.sh -O - | /bin/sh", "type": "thirdparty", "desc": "Auto DCW key add"},
    {"phase": 99, "name": "LinuxsatPanel", "command": "wget -q --no-check-certificate https://raw.githubusercontent.com/Belfagor2005/LinuxsatPanel/main/installer.sh -O - | /bin/sh", "type": "thirdparty", "desc": "Linuxsat Panel"},
    {"phase": 99, "name": "SubsSupport", "command": "wget -q --no-check-certificate https://github.com/popking159/ssupport/raw/main/subssupport-install.sh -O - | /bin/sh", "type": "thirdparty", "desc": "SubsSupport"},
    {"phase": 99, "name": "NewVirtualKeyBoard", "command": "wget https://raw.githubusercontent.com/fairbird/NewVirtualKeyBoard/main/installer.sh -O - | /bin/sh", "type": "thirdparty", "desc": "New Virtual KeyBoard"},
]